# Generated by Django 5.2.11 on 2026-03-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_deliveryoption_currency_remove_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoption',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryoption',
            name='updated_at',
        ),
    ]
