# Generated by Django 5.2.11 on 2026-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='service',
            name='currency',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Generic', max_length=100),
        ),
    ]
